### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by morganKa** [MewesK/TwigSpreadsheetBundle#10]
Hi,

At first, thanks a lot you this bundle !
Is there any configuration in order to set charset ? I have some issues with accented characters, which come differently up to output format.

Thanks !

**Comment by MewesK** [comment]
Hi,

the library PhpSpreadsheet which my bundle is based on does not allow a global encoding setting. It will just use whatever Twig is producing. So if you have encoding problems you should check your PHP, Symfony and Twig first.

If that won't fix it, just provide an example for me and I'll take a look!

**Comment by morganKa** [comment]
Thanks for your answer. Unfortunately, this does not fix my problem.
With something as simple as the following :

Controller
```php
    /**
     * @Route("/export.{_format}", name="export", defaults={"_format"="xls"}, requirements={"_format"="csv|xls|xlsx"})
     * @Template("templates/export.xls.twig")
     */
    public function export()
    {
        $titles = ["Head1", "Head2"];
        $lines = ["Data é 11||Data12", "Data21||Data22"];

        return ["titles" => $titles, "lines" => $lines];

    }
```

Template
```twig
{% xlsdocument %}
    {% xlssheet 'export' %}

        {% xlsrow %}
            {% for title in titles %}
                {% xlscell %}{{ title }}{% endxlscell %}
            {% endfor %}
        {% endxlsrow %}


        {% for line in lines %}
            {% set lineTab = line | split("||") %}
            {% xlsrow %}
                {% for data in lineTab %}
                    {% xlscell %}{{ data }}{% endxlscell %}
                {% endfor %}
            {% endxlsrow %}
        {% endfor %}

    {% endxlssheet %}
{% endxlsdocument %}
```
Both files are encorded in UTF-8.

I have different result up to _format parameter :
 for /export.xls :


Head1 | Head2
-- | --
Data é 11 | Data12
Data21 | Data22

and for /export.csv :


Head1 | Head2
-- | --
Data Ã© 11 | Data12
Data21 | Data22

If you have any clue...
Thanks for your help !
