### ISSUE TITLE
CSV separator

### ISSUE THREAD

**Issue by morganKa** [MewesK/TwigSpreadsheetBundle#11]
Hey,

Is there any parameter to set CSV separator (to semicolon, for example) ?

Thanks !

**Comment by MewesK** [comment]
I've added all properties of PhpOffice\PhpSpreadsheet\Writer\Csv.php to the bundle configuration. You can now change the parameters. You can find an example in the documentation.

Thanks for the suggestion, will be part of version 1.1. Let me know if everything works as expected!
