### ISSUE TITLE
Incorrect cache directory for images

### ISSUE THREAD

**Issue by technetium** [MewesK/TwigSpreadsheetBundle#13]
When using the xlsdrawing tag with an image path e.g. ` {% xlsdrawing 'directory/image.png' %}`

The following exception is thrown:

`An exception has been thrown during the rendering of a template ("Failed to create ""/tmp/symfony/cache/dev/spreadsheet/bitmap"": mkdir(): Input/output error.").`

This is causes because the default value of the bitmap directory is surrounded with double quotes.

Removing these quotes (and clearing the cache) will solve this problem

**Comment by MewesK** [comment]
Thanks for the bugfix, will be added to version 1.1!
