### ISSUE TITLE
bug pre_calculate_formulas

### ISSUE THREAD

**Issue by mikysan** [MewesK/TwigSpreadsheetBundle#15]
On [src/Wrapper/DocumentWrapper.php:120](https://github.com/MewesK/TwigSpreadsheetBundle/blob/1.0/src/Wrapper/DocumentWrapper.php) you check $this->attributes['preCalculateFormulas'] but actually in the __constructor of the class that attribute (fetched from mewes_k_twig_spreadsheet.yaml) is saved with the key 'pre_calculate_formulas' in snake_case and not in pascalCase.

I am using "mewesk/twig-spreadsheet-bundle": "^1.0" and "symfony/framework-bundle": "^4.1", I don't know if the way symfony pass this attribute has changed through versions but for sure you should able to reproduce the error and check by yourself. I didn't make a PR 'cause I don't know how you prefer to fix this (assuming that this feature has worked in the past and you don't want to break compatibility).

Cheers!

**Comment by MewesK** [comment]
You're right, I messed that up during one the many refactorings. It's fixed now and I've added a unit test to prevent that from happening. Will be part of version 1.1., thanks a lot for the ticket!
