### ISSUE TITLE
Add xlsrowindex

### ISSUE THREAD

**Issue by technetium** [MewesK/TwigSpreadsheetBundle#16]
It would be very convenient to have a function that returns the current row index.
When using this function the coordinates of images and merges don't have to be changed manually when lines are added or removed.

The commit df1eb8babd410da490460bedecb85f5938911d06 will implement this function

**Comment by MewesK** [comment]
Thanks for the suggestion, will be added to version 1.1!
I used the opportunity to improve the internal index handling, so I had to change your code, just in case you're wondering. I also added xlscellindex to be complete.
