### ISSUE TITLE
Can't style border in spreadsheet with twigspreadsheetbundle

### ISSUE THREAD

**Issue by deshiloh** [MewesK/TwigSpreadsheetBundle#21]
Here is the code I'm using, but it's not working (alignment works, not the borders)

```
{% set style =  {
            alignment : {
                horizontal: 'center'
            },
            borders: {
                bottom: {
                    style: 'thin',
                    color: {
                        rgb: '000000'
                    }
                }
            }
        }
        %}

{% xlscell { style: style } %}Date{% endxlscell %}
```

**Comment by deshiloh** [comment]
up

**Comment by koplusm** [comment]
> Here is the code I'm using, but it's not working (alignment works, not the borders)
> 
> ```
> {% set style =  {
>             alignment : {
>                 horizontal: 'center'
>             },
>             borders: {
>                 bottom: {
>                     style: 'thin',
>                     color: {
>                         rgb: '000000'
>                     }
>                 }
>             }
>         }
>         %}
> 
> {% xlscell { style: style } %}Date{% endxlscell %}
> ```

lots of time has passed but use borderStyle: 'thin' instead of style: 'thin'
```
      bottom: {
        borderStyle: 'thin',
        color: {
          rgb: '000000'
        }
      },
```
