### ISSUE TITLE
Latest phpspreadsheet version

### ISSUE THREAD

**Issue by haroldmodesto** [MewesK/TwigSpreadsheetBundle#7]
Any chance this bundle can be upgraded to the latest release of phpoffice/spreadsheet (currently 1.2) ? 

From https://github.com/PHPOffice/PhpSpreadsheet/releases it appears the transition from 1.0.0-beta2 to 1.2.0 only has one breaking change:

> BREAKING CHANGE
> Constant TYPE_DOUGHTNUTCHART is now TYPE_DOUGHNUTCHART.
> 

This twig integration looks to be super useful but the beta dependency is a deal breaker for me.

**Comment by MewesK** [comment]
FYI: Version 1.0 will be released this week. I'm waiting for bug-fix release of PhpSpreadsheet, my pull request was already merged.
